local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: "src/uploads"
public_folder: "/uploads"
collections:
  - name: "work"
    label: "Work"
    folder: "src/work"
    create: true
    slug: "{{handle}}"
    sortable_fields:
      - "title"
      - "date"
    view_filters:
      - label: "UX/UI Design"
        field: "category"
        pattern: "ui-ux-design"
      - label: "Logotype"
        field: "category"
        pattern: "logotype"
      - label: "Animation/Motion"
        field: "category"
        pattern: "animation-motion"
      - label: "Social Media"
        field: "category"
        pattern: "social-media"
      - label: "Illustration"
        field: "category"
        pattern: "illustration"
    view_groups:
      - label: "Category"
        field: "category"
      - label: "Favorite"
        field: "favorite"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "work.webc"

      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "work"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Slug"
        name: "handle"
        widget: "string"

      - label: "Category"
        name: "category"
        widget: "select"
        options: 
          - label: "UX/UI Design"
            value: "ui-ux-design"
          - label: "Logotype"
            value: "logotype"
          - label: "Animation/Motion"
            value: "animation-motion"
          - label: "Social Media"
            value: "social-media"
          - label: "Illustration"
            value: "illustration"

      - label: "Favorite"
        name: "favorite"
        widget: "boolean"
        default: false

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Cover Image"
        name: "coverImage"
        widget: "image"

      - label: "Cover Video"
        name: "coverVideo"
        widget: "file"
        required: false

      - label: "Brief"
        name: "brief"
        widget: "text"

      - label: "Role"
        name: "role"
        widget: "text"

      - label: "More link"
        name: "more"
        widget: "string"

      - label: "Demos"
        name: "demos"
        widget: "list"
        fields:
          - label: "Demo"
            name: "demo"
            widget: "object"
            fields:
              - label: "Image"
                name: "image"
                widget: "image"
                required: false

              - label: "Video"
                name: "video"
                widget: "file"
                required: false

              - label: "Caption"
                name: "caption"
                widget: "string"
                required: false

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Results"
        name: "results"
        widget: "text"

      - label: "Tools"
        name: "tools"
        widget: "list"
        allow_add: true
        field:
          label: "Tool" 
          name: "tool"
          widget: "string"

      - label: "Open Graph"
        name: "og"
        widget: "object"
        fields:
          - label: "og:title"
            name: "opengraph"
            widget: "boolean"
            default: true
            required: false

          - label: "og:title"
            name: "title"
            widget: "string"
            required: false

          - label: "og:image"
            name: "image"
            widget: "image"
            required: false
            hint: "1200 x 630 pixels recommended"

          - label: "og:description"
            name: "description"
            widget: "text"
            required: false

          - label: "og:url"
            name: "url"
            widget: "boolean"
            default: true
            required: false
            hint: "Generated automatically if enabled"

          - label: "og:type"
            name: "type"
            widget: "string"
            default: website
            required: false

          - label: "og:locale"
            name: "locale"
            widget: "string"
            default: en_US
            required: false

          - label: "og:site_name"
            name: "site_name"
            widget: "string"
            required: false

          - label: "twitter:card"
            name: "twitter"
            widget: "boolean"
            default: true
            required: false
            hint: "Generated automatically from og:* if enabled"

          - label: "twitter:site"
            name: "site"
            widget: "string"
            required: false

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/index.md"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "home.webc"

          - label: "Body"
            name: "body"
            widget: "markdown"

          - label: "Video"
            name: "video"
            widget: "file"
            required: false

          - label: "Poster"
            name: "poster"
            widget: "image"

          - label: "Open Graph"
            name: "og"
            widget: "object"
            fields:
              - label: "og:title"
                name: "opengraph"
                widget: "boolean"
                default: true
                required: false

              - label: "og:title"
                name: "title"
                widget: "string"
                required: false

              - label: "og:image"
                name: "image"
                widget: "image"
                required: false
                hint: "1200 x 630 pixels recommended"

              - label: "og:description"
                name: "description"
                widget: "text"
                required: false

              - label: "og:url"
                name: "url"
                widget: "boolean"
                default: true
                required: false
                hint: "Generated automatically if enabled"

              - label: "og:type"
                name: "type"
                widget: "string"
                default: website
                required: false

              - label: "og:locale"
                name: "locale"
                widget: "string"
                default: en_US
                required: false

              - label: "og:site_name"
                name: "site_name"
                widget: "string"
                required: false

              - label: "twitter:card"
                name: "twitter"
                widget: "boolean"
                default: true
                required: false
                hint: "Generated automatically from og:* if enabled"

              - label: "twitter:site"
                name: "site"
                widget: "string"
                required: false

      - label: "About"
        name: "about"
        file: "src/about/index.md"
        fields:
          - label: "Layout"
            name: "layout"
            widget: "hidden"
            default: "home.webc"

          - label: "Body"
            name: "body"
            widget: "markdown"

          - label: "Video"
            name: "video"
            widget: "file"
            required: false

          - label: "Poster"
            name: "poster"
            widget: "image"

          - label: "Open Graph"
            name: "og"
            widget: "object"
            fields:
              - label: "og:title"
                name: "opengraph"
                widget: "boolean"
                default: true
                required: false

              - label: "og:title"
                name: "title"
                widget: "string"
                required: false

              - label: "og:image"
                name: "image"
                widget: "image"
                required: false
                hint: "1200 x 630 pixels recommended"

              - label: "og:description"
                name: "description"
                widget: "text"
                required: false

              - label: "og:url"
                name: "url"
                widget: "boolean"
                default: true
                required: false
                hint: "Generated automatically if enabled"

              - label: "og:type"
                name: "type"
                widget: "string"
                default: website
                required: false

              - label: "og:locale"
                name: "locale"
                widget: "string"
                default: en_US
                required: false

              - label: "og:site_name"
                name: "site_name"
                widget: "string"
                required: false

              - label: "twitter:card"
                name: "twitter"
                widget: "boolean"
                default: true
                required: false
                hint: "Generated automatically from og:* if enabled"

              - label: "twitter:site"
                name: "site"
                widget: "string"
                required: false

  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - label: "General"
        name: "general"
        file: "src/_data/global.json"
        fields:
          - label: "Socials"
            name: "socials"
            widget: "object"
            fields:
              - label: "LinkedIn"
                name: "linkedin"
                widget: "string"

              - label: "Behance"
                name: "behance"
                widget: "string"

              - label: "Email"
                name: "email"
                widget: "string"

          - label: "Buttons"
            name: "buttons"
            widget: "object"
            fields:
              - label: "Get in Touch"
                name: "getInTouch"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "string"

                  - label: "Link"
                    name: "link"
                    widget: "string"

              - label: "Download my resume"
                name: "resume"
                widget: "object"
                fields:
                  - label: "Text"
                    name: "text"
                    widget: "string"

                  - label: "Resume"
                    name: "link"
                    widget: "file"